In [1]:
import pandas as pd

In [2]:
orders = pd.read_csv("/Users/abhijeetsinghparihar/Desktop/Projects/Supply Chain Project/CartIQ/data/raw/orders.csv")

In [3]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [4]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                object
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), object(1)
memory usage: 182.7+ MB

In [5]:
orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [6]:
orders['order_number']

0           1
1           2
2           3
3           4
4           5
           ..
3421078    10
3421079    11
3421080    12
3421081    13
3421082    14
Name: order_number, Length: 3421083, dtype: int64

In [7]:
orders[orders["order_number"] == 1]

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
11,2168274,2,prior,1,2,11,NaN
26,1374495,3,prior,1,1,14,NaN
39,3343014,4,prior,1,6,11,NaN
45,2717275,5,prior,1,3,12,NaN
...,...,...,...,...,...,...,...
3420930,969311,206205,prior,1,4,12,NaN
3420934,3189322,206206,prior,1,3,18,NaN
3421002,2166133,206207,prior,1,6,19,NaN
3421019,2227043,206208,prior,1,1,15,NaN
3421069,3154581,206209,prior,1,3,11,NaN

In [8]:
orders[["order_id", "days_since_prior_order"]][orders["days_since_prior_order"].isna()].sample(10)

         order_id  days_since_prior_order
3116835   1078615                     NaN
297989      92459                     NaN
472917    2377693                     NaN
1949147   1188679                     NaN
1239746   2853213                     NaN
1012877   2755352                     NaN
144817     119626                     NaN
177401    3091832                     NaN
441793     793518                     NaN
2346449   1301102                     NaN

In [9]:
orders.sort_values(by="user_id")

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
10,1187899,1,train,11,4,8,14.0
9,2550362,1,prior,10,4,8,30.0
7,3108588,1,prior,8,1,14,14.0
6,550135,1,prior,7,1,9,20.0
...,...,...,...,...,...,...,...
3421071,1542354,206209,prior,3,5,11,30.0
3421069,3154581,206209,prior,1,3,11,NaN
3421081,2977660,206209,prior,13,1,12,7.0
3421074,3186442,206209,prior,6,0,16,3.0
3421082,272231,206209,train,14,6,14,30.0

In [10]:
orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [11]:
orders["user_id"].value_counts()

user_id
152340    100
185641    100
185524    100
81678     100
70922     100
         ...
13046       4
70208       4
111440      4
31762       4
47980       4
Name: count, Length: 206209, dtype: int64

## Finalising the order_history_master.csv

In [12]:
random_order_id = orders[orders['eval_set'] == 'prior']['order_id'].sample(n=200000, random_state=42)

In [13]:
order_data = orders[orders['order_id'].isin(random_order_id)][[ 'order_id', 
                                                                'order_dow',
                                                                'order_hour_of_day', 
                                                                'days_since_prior_order',
                                                                'order_number']]

In [14]:
order_data.head()

,order_id,order_dow,order_hour_of_day,days_since_prior_order,order_number
13,1901567,1,10,3.0,3
29,2037211,2,18,20.0,4
31,1972919,0,16,7.0,6
39,3343014,6,11,NaN,1
58,3321109,5,18,3.0,5

In [15]:
order_products_prior = pd.read_csv("/Users/abhijeetsinghparihar/Desktop/Projects/Supply Chain Project/CartIQ/data/raw/order_products_prior.csv")

In [16]:
order_products_prior.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 4 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   product_id         int64
 2   add_to_cart_order  int64
 3   reordered          int64
dtypes: int64(4)
memory usage: 989.8 MB

In [17]:
merge_order_id_data = pd.merge(order_data, order_products_prior, on='order_id')

In [18]:
merge_order_id_data[merge_order_id_data['order_id'] == 1901567]

,order_id,order_dow,order_hour_of_day,days_since_prior_order,order_number,product_id,add_to_cart_order,reordered
0,1901567,1,10,3.0,3,47766,1,1
1,1901567,1,10,3.0,3,32792,2,1
2,1901567,1,10,3.0,3,20574,3,1
3,1901567,1,10,3.0,3,7781,4,0
4,1901567,1,10,3.0,3,28874,5,0

In [19]:
products = pd.read_csv("/Users/abhijeetsinghparihar/Desktop/Projects/Supply Chain Project/CartIQ/data/raw/products.csv")

In [20]:
final_product_merge_data = pd.merge(merge_order_id_data, products, on='product_id', how='inner')

In [21]:
print(order_data.shape)
print(merge_order_id_data.shape)
print(final_product_merge_data.shape)

(200000, 5)
(2019713, 8)
(2019713, 11)

In [22]:
final_product_merge_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2019713 entries, 0 to 2019712
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   order_dow               int64
 2   order_hour_of_day       int64
 3   days_since_prior_order  float64
 4   order_number            int64
 5   product_id              int64
 6   add_to_cart_order       int64
 7   reordered               int64
 8   product_name            object
 9   aisle_id                int64
 10  department_id           int64
dtypes: float64(1), int64(9), object(1)
memory usage: 169.5+ MB

In [23]:
## chnaging days_since_prior_order 

final_product_merge_data['days_since_prior_order'][final_product_merge_data['days_since_prior_order'].isna()] = -1

/var/folders/0l/6zfkt4257nx_lmh9vlt1l2gw0000gn/T/ipykernel_73308/3810924189.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  final_product_merge_data['days_since_prior_order'][final_product_merge_data['days_since_prior_order'].isna()] = -1
/var/folders/0l/6zfkt4257nx_lmh9vlt1l2gw0000gn/T/ipykernel_73308/3810924189.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_product_merge_data['days_since_prior_order'][final_product_merge_data['days_since_prior_order'].isna()] = -1

In [24]:
final_product_merge_data[final_product_merge_data['days_since_prior_order'].isna()]

Empty DataFrame
Columns: [order_id, order_dow, order_hour_of_day, days_since_prior_order, order_number, product_id, add_to_cart_order, reordered, product_name, aisle_id, department_id]
Index: []